/* eslint-disable array-bracket-spacing, no-multi-spaces, indent, @typescript-eslint/indent */

import { ObjectKeys } from '../../mol-util/type-helpers';
import { StandardBases } from './reference-conformers-pdbs';

export type Ring = 'purine' | 'pyrimidine' | 'PSU';

export const NtCs = [
    'AA00',
    'AA01',
    'AA02',
    'AA03',
    'AA04',
    'AA05',
    'AA06',
    'AA07',
    'AA08',
    'AA09',
    'AA10',
    'AA11',
    'AA12',
    'AA13',
    'AB01',
    'AB02',
    'AB03',
    'AB04',
    'AB05',
    'BA01',
    'BA05',
    'BA09',
    'BA08',
    'BA10',
    'BA13',
    'BA16',
    'BA17',
    'BB00',
    'BB01',
    'BB17',
    'BB02',
    'BB03',
    'BB11',
    'BB16',
    'BB04',
    'BB05',
    'BB07',
    'BB08',
    'BB10',
    'BB12',
    'BB13',
    'BB14',
    'BB15',
    'BB20',
    'IC01',
    'IC02',
    'IC03',
    'IC04',
    'IC05',
    'IC06',
    'IC07',
    'OP01',
    'OP02',
    'OP03',
    'OP04',
    'OP05',
    'OP06',
    'OP07',
    'OP08',
    'OP09',
    'OP10',
    'OP11',
    'OP12',
    'OP13',
    'OP14',
    'OP15',
    'OP16',
    'OP17',
    'OP18',
    'OP19',
    'OP20',
    'OP21',
    'OP22',
    'OP23',
    'OP24',
    'OP25',
    'OP26',
    'OP27',
    'OP28',
    'OP29',
    'OP30',
    'OP31',
    'OPS1',
    'OP1S',
    'AAS1',
    'AB1S',
    'AB2S',
    'BB1S',
    'BB2S',
    'BBS1',
    'ZZ01',
    'ZZ02',
    'ZZ1S',
    'ZZ2S',
    'ZZS1',
    'ZZS2',
] as const;
export type NtCs = typeof NtCs[number];

export type BaseProps = [ring: Ring, isDeoxyribose: boolean, parentBase: StandardBases];

export const KnownBasesProps = {
    '0AD': [ 'purine', true,  'G' ],
    '0AV': [ 'purine', true,  'A' ],
    '0SP': [ 'purine', true,  'A' ],
    '0UH': [ 'purine', true,  'G' ],
    '12A': [ 'purine', false, 'A' ],
    '18M': [ 'purine', false, 'G' ],
    '1AP': [ 'purine', true,  'A' ],
    '1MA': [ 'purine', false, 'A' ],
    '1MG': [ 'purine', false, 'G' ],
    '2BU': [ 'purine', true,  'A' ],
    '2EG': [ 'purine', false, 'G' ],
    '2MA': [ 'purine', false, 'A' ],
    '2MG': [ 'purine', false, 'G' ],
    '2PR': [ 'purine', true,  'G' ],
    '6FK': [ 'purine', true,  'G' ],
    '6HA': [ 'purine', true,  'A' ],
    '6HB': [ 'purine', true,  'A' ],
    '6HG': [ 'purine', true,  'G' ],
    '6IA': [ 'purine', false, 'A' ],
    '6MA': [ 'purine', false, 'A' ],
    '6MC': [ 'purine', false, 'A' ],
    '6MT': [ 'purine', false, 'A' ],
    '6OG': [ 'purine', true,  'G' ],
    '6PO': [ 'purine', true,  'G' ],
    '7AT': [ 'purine', false, 'A' ],
    '7BG': [ 'purine', true,  'G' ],
    '7DA': [ 'purine', true,  'A' ],
    '7GU': [ 'purine', true,  'G' ],
    '7MG': [ 'purine', false, 'G' ],
    '8AA': [ 'purine', false, 'G' ],
    '8BA': [ 'purine', true,  'A' ],
    '8FG': [ 'purine', true,  'G' ],
    '8MG': [ 'purine', true,  'G' ],
    '8OG': [ 'purine', true,  'G' ],
    '8PY': [ 'purine', true,  'G' ],
      'A': [ 'purine', false, 'A' ],
    'A23': [ 'purine', false, 'A' ],
    'A2L': [ 'purine', false, 'A' ],
    'A2M': [ 'purine', false, 'A' ],
    'A44': [ 'purine', false, 'A' ],
    'A5L': [ 'purine', true,  'A' ],
    'A5O': [ 'purine', false, 'A' ],
    'A6A': [ 'purine', false, 'A' ],
    'A6G': [ 'purine', false, 'G' ],
    'A7E': [ 'purine', false, 'A' ],
    'A9Z': [ 'purine', false, 'A' ],
    'ABR': [ 'purine', true,  'A' ],
    'ABS': [ 'purine', true,  'A' ],
    'AET': [ 'purine', false, 'A' ],
    'AF2': [ 'purine', true,  'A' ],
    'AFG': [ 'purine', true,  'G' ],
    'AP7': [ 'purine', false, 'A' ],
    'ATP': [ 'purine', false, 'A' ],
    'AVC': [ 'purine', false, 'A' ],
    'B8K': [ 'purine', false, 'G' ],
    'B8W': [ 'purine', false, 'G' ],
    'B9B': [ 'purine', false, 'G' ],
    'BGH': [ 'purine', false, 'G' ],
    'BGM': [ 'purine', true,  'G' ],
    'C6G': [ 'purine', true,  'G' ],
    'CG1': [ 'purine', false, 'G' ],
     'DA': [ 'purine', true,  'A' ],
    'DCG': [ 'purine', true,  'G' ],
    'DFG': [ 'purine', true,  'G' ],
     'DG': [ 'purine', true,  'G' ],
    'DZM': [ 'purine', true,  'A' ],
      'E': [ 'purine', true,  'A' ],
    'E1X': [ 'purine', true,  'A' ],
    'E6G': [ 'purine', false, 'G' ],
    'E7G': [ 'purine', false, 'G' ],
    'EDA': [ 'purine', true,  'A' ],
    'EHG': [ 'purine', true,  'G' ],
    'F74': [ 'purine', true,  'G' ],
    'FDG': [ 'purine', true,  'G' ],
    'FMG': [ 'purine', true,  'G' ],
    'G25': [ 'purine', false, 'G' ],
    'G2L': [ 'purine', false, 'G' ],
    'G48': [ 'purine', false, 'G' ],
    'G7M': [ 'purine', false, 'G' ],
    'GAO': [ 'purine', false, 'G' ],
    'GF2': [ 'purine', true,  'G' ],
    'GMS': [ 'purine', true,  'G' ],
    'GOM': [ 'purine', false, 'G' ],
    'GRB': [ 'purine', false, 'G' ],
    'GSR': [ 'purine', true,  'G' ],
    'GSS': [ 'purine', true,  'G' ],
    'GX1': [ 'purine', true,  'G' ],
    'HN0': [ 'purine', true,  'G' ],
    'HN1': [ 'purine', true,  'G' ],
     'IG': [ 'purine', false, 'G' ],
    'IGU': [ 'purine', true,  'G' ],
    'KAG': [ 'purine', false, 'G' ],
    'LCG': [ 'purine', true,  'G' ],
     'LG': [ 'purine', false, 'G' ],
    'LGP': [ 'purine', true,  'G' ],
    'M1G': [ 'purine', true,  'G' ],
    'M2G': [ 'purine', false, 'G' ],
    'M7A': [ 'purine', false, 'A' ],
    'MA6': [ 'purine', false, 'A' ],
    'MA7': [ 'purine', true,  'A' ],
    'MAD': [ 'purine', false, 'A' ],
    'MFO': [ 'purine', true,  'G' ],
    'MG1': [ 'purine', true,  'G' ],
    'MGV': [ 'purine', false, 'G' ],
    'MHG': [ 'purine', false, 'G' ],
    'MIA': [ 'purine', false, 'A' ],
    'MRG': [ 'purine', true,  'G' ],
    'MTU': [ 'purine', false, 'A' ],
    'N6G': [ 'purine', false, 'G' ],
    'O2G': [ 'purine', false, 'G' ],
    'OGX': [ 'purine', true,  'G' ],
    'OMG': [ 'purine', false, 'G' ],
    'P5P': [ 'purine', false, 'A' ],
    'P7G': [ 'purine', false, 'G' ],
    'PG7': [ 'purine', true,  'G' ],
    'PGN': [ 'purine', true,  'G' ],
    'PGP': [ 'purine', false, 'G' ],
    'PPW': [ 'purine', true,  'G' ],
    'PR5': [ 'purine', false, 'A' ],
    'PRN': [ 'purine', true,  'A' ],
    'QUO': [ 'purine', false, 'G' ],
      'R': [ 'purine', true,  'A' ],
    'RDG': [ 'purine', true,  'G' ],
    'RIA': [ 'purine', false, 'A' ],
    'S6G': [ 'purine', true,  'G' ],
    'SDH': [ 'purine', true,  'G' ],
    'T6A': [ 'purine', false, 'A' ],
    'V3L': [ 'purine', false, 'A' ],
      'X': [ 'purine', true,  'G' ],
    'XPB': [ 'purine', true,  'G' ],
    'XUA': [ 'purine', true,  'A' ],
    'XUG': [ 'purine', true,  'G' ],
     'YG': [ 'purine', false, 'G' ],
    'YYG': [ 'purine', false, 'G' ],
    'AD2': [ 'purine', true,  'A' ],
    'A3P': [ 'purine', false, 'A' ],
    'DDG': [ 'purine', true,  'G' ],
    'GDP': [ 'purine', false, 'G' ],
    'GFL': [ 'purine', true,  'G' ],
      'G': [ 'purine', false, 'G' ],
    'GNE': [ 'purine', true,  'G' ],
    'GTP': [ 'purine', false, 'G' ],
    'TGP': [ 'purine', true,  'G' ],
    '2FI': [ 'purine', true,  'A' ],
    '2DA': [ 'purine', true,  'A' ],
     'DI': [ 'purine', true,  'A' ],

    '0AP': [ 'pyrimidine', true,  'C' ],
    '0AU': [ 'pyrimidine', true,  'U' ],
    '125': [ 'pyrimidine', false, 'U' ],
    '126': [ 'pyrimidine', false, 'U' ],
    '127': [ 'pyrimidine', false, 'U' ],
    '18Q': [ 'pyrimidine', true,  'U' ],
    '1CC': [ 'pyrimidine', true,  'C' ],
    '1FC': [ 'pyrimidine', true,  'C' ],
    '1RN': [ 'pyrimidine', false, 'U' ],
    '2AT': [ 'pyrimidine', true,  'T' ],
    '2AU': [ 'pyrimidine', false, 'U' ],
    '2BT': [ 'pyrimidine', true,  'T' ],
    '2GT': [ 'pyrimidine', true,  'T' ],
    '2MU': [ 'pyrimidine', false, 'U' ],
    '2NT': [ 'pyrimidine', true,  'T' ],
    '2OM': [ 'pyrimidine', false, 'U' ],
    '2OT': [ 'pyrimidine', true,  'T' ],
    '2ST': [ 'pyrimidine', true,  'T' ],
    '3AU': [ 'pyrimidine', false, 'U' ],
    '3ME': [ 'pyrimidine', false, 'U' ],
    '3MU': [ 'pyrimidine', false, 'U' ],
    '47C': [ 'pyrimidine', true,  'C' ],
    '4OC': [ 'pyrimidine', false, 'C' ],
    '4PC': [ 'pyrimidine', true,  'C' ],
    '4PD': [ 'pyrimidine', true,  'C' ],
    '4PE': [ 'pyrimidine', true,  'C' ],
    '4SU': [ 'pyrimidine', false, 'U' ],
    '4U3': [ 'pyrimidine', true,  'C' ],
    '5BU': [ 'pyrimidine', false, 'U' ],
    '5CM': [ 'pyrimidine', true,  'C' ],
    '5FC': [ 'pyrimidine', true,  'C' ],
    '5HC': [ 'pyrimidine', true,  'C' ],
    '5HM': [ 'pyrimidine', false, 'C' ],
    '5HU': [ 'pyrimidine', true,  'U' ],
    '5IC': [ 'pyrimidine', false, 'C' ],
    '5IT': [ 'pyrimidine', true,  'T' ],
    '5IU': [ 'pyrimidine', true,  'U' ],
    '5MC': [ 'pyrimidine', false, 'C' ],
    '5MU': [ 'pyrimidine', false, 'U' ],
    '5NC': [ 'pyrimidine', true,  'C' ],
    '5PC': [ 'pyrimidine', true,  'C' ],
    '5PY': [ 'pyrimidine', true,  'T' ],
    '5SE': [ 'pyrimidine', true,  'U' ],
    '64T': [ 'pyrimidine', true,  'T' ],
    '6HC': [ 'pyrimidine', true,  'C' ],
    '6HT': [ 'pyrimidine', true,  'T' ],
    '70U': [ 'pyrimidine', false, 'U' ],
    '75B': [ 'pyrimidine', false, 'U' ],
    '77Y': [ 'pyrimidine', true,  'U' ],
    '85Y': [ 'pyrimidine', false, 'U' ],
    '8DT': [ 'pyrimidine', true,  'U' ],
    '8RO': [ 'pyrimidine', true,  'C' ],
    '94O': [ 'pyrimidine', true,  'T' ],
    '9QV': [ 'pyrimidine', false, 'U' ],
    'A5M': [ 'pyrimidine', false, 'C' ],
    'A6C': [ 'pyrimidine', false, 'C' ],
    'A6U': [ 'pyrimidine', false, 'U' ],
    'ATD': [ 'pyrimidine', true,  'T' ],
    'ATL': [ 'pyrimidine', true,  'T' ],
    'B7C': [ 'pyrimidine', true,  'C' ],
    'B8Q': [ 'pyrimidine', false, 'C' ],
    'B8T': [ 'pyrimidine', false, 'C' ],
    'B9H': [ 'pyrimidine', false, 'C' ],
    'BOE': [ 'pyrimidine', true,  'T' ],
    'BRU': [ 'pyrimidine', true,  'U' ],
    'C25': [ 'pyrimidine', false, 'C' ],
    'C2L': [ 'pyrimidine', false, 'C' ],
    'C34': [ 'pyrimidine', true,  'C' ],
    'C43': [ 'pyrimidine', false, 'C' ],
    'C5L': [ 'pyrimidine', false, 'C' ],
    'CAR': [ 'pyrimidine', true,  'C' ],
    'CB2': [ 'pyrimidine', true,  'C' ],
    'CBR': [ 'pyrimidine', true,  'C' ],
    'CCC': [ 'pyrimidine', false, 'C' ],
    'CDW': [ 'pyrimidine', true,  'C' ],
     'CH': [ 'pyrimidine', false, 'C' ],
    'CTG': [ 'pyrimidine', true,  'T' ],
    'D00': [ 'pyrimidine', true,  'C' ],
     'DC': [ 'pyrimidine', true,  'C' ],
    'DDN': [ 'pyrimidine', true,  'U' ],
    'DFC': [ 'pyrimidine', true,  'C' ],
    'DHU': [ 'pyrimidine', false, 'U' ],
    'DNR': [ 'pyrimidine', true,  'C' ],
    'DRT': [ 'pyrimidine', true,  'T' ],
     'DT': [ 'pyrimidine', true,  'T' ],
     'DU': [ 'pyrimidine', true,  'U' ],
    'DUZ': [ 'pyrimidine', true,  'U' ],
    'E3C': [ 'pyrimidine', false, 'C' ],
    'EIT': [ 'pyrimidine', true,  'T' ],
    'F3H': [ 'pyrimidine', true,  'T' ],
    'GMU': [ 'pyrimidine', true,  'U' ],
    'H2U': [ 'pyrimidine', false, 'U' ],
    'HEU': [ 'pyrimidine', true,  'U' ],
    'I4U': [ 'pyrimidine', false, 'U' ],
    'I5C': [ 'pyrimidine', true,  'C' ],
     'IC': [ 'pyrimidine', false, 'C' ],
    'IMC': [ 'pyrimidine', true,  'C' ],
     'IU': [ 'pyrimidine', false, 'U' ],
    'JDT': [ 'pyrimidine', true,  'T' ],
    'JMH': [ 'pyrimidine', false, 'C' ],
     'LC': [ 'pyrimidine', false, 'C' ],
    'LHU': [ 'pyrimidine', false, 'U' ],
    'LSH': [ 'pyrimidine', true,  'T' ],
    'LST': [ 'pyrimidine', true,  'T' ],
    'M5M': [ 'pyrimidine', false, 'C' ],
    'MNU': [ 'pyrimidine', false, 'U' ],
    'N5M': [ 'pyrimidine', false, 'C' ],
    'NCU': [ 'pyrimidine', true,  'C' ],
    'NDU': [ 'pyrimidine', true,  'U' ],
    'NMS': [ 'pyrimidine', true,  'T' ],
    'NMT': [ 'pyrimidine', true,  'T' ],
    'NTT': [ 'pyrimidine', true,  'T' ],
    'OHU': [ 'pyrimidine', true,  'U' ],
    'OMC': [ 'pyrimidine', false, 'C' ],
    'OMU': [ 'pyrimidine', false, 'U' ],
    'ONE': [ 'pyrimidine', false, 'U' ],
    'P2T': [ 'pyrimidine', true,  'T' ],
    'P4U': [ 'pyrimidine', false, 'U' ],
    'PDU': [ 'pyrimidine', true,  'U' ],
    'PST': [ 'pyrimidine', true,  'T' ],
    'PYO': [ 'pyrimidine', false, 'U' ],
    'RPC': [ 'pyrimidine', false, 'C' ],
    'RSQ': [ 'pyrimidine', false, 'C' ],
    'S2M': [ 'pyrimidine', true,  'T' ],
    'S4U': [ 'pyrimidine', false, 'U' ],
    'SMT': [ 'pyrimidine', true,  'T' ],
    'SUR': [ 'pyrimidine', false, 'U' ],
    'T39': [ 'pyrimidine', true,  'T' ],
    'T3P': [ 'pyrimidine', true,  'T' ],
    'T4S': [ 'pyrimidine', true,  'T' ],
    'T5O': [ 'pyrimidine', true,  'U' ],
    'T5S': [ 'pyrimidine', true,  'T' ],
    'TA3': [ 'pyrimidine', true,  'T' ],
    'TAF': [ 'pyrimidine', true,  'T' ],
    'TC1': [ 'pyrimidine', true,  'C' ],
    'TDY': [ 'pyrimidine', true,  'T' ],
    'TED': [ 'pyrimidine', true,  'T' ],
    'TFE': [ 'pyrimidine', true,  'T' ],
    'TLC': [ 'pyrimidine', true,  'T' ],
    'TLN': [ 'pyrimidine', true,  'U' ],
    'TTM': [ 'pyrimidine', true,  'T' ],
    'U25': [ 'pyrimidine', false, 'U' ],
    'U2L': [ 'pyrimidine', false, 'U' ],
    'U2N': [ 'pyrimidine', true,  'U' ],
    'U36': [ 'pyrimidine', false, 'U' ],
    'U8U': [ 'pyrimidine', false, 'U' ],
    'UAR': [ 'pyrimidine', false, 'U' ],
    'UBI': [ 'pyrimidine', true,  'U' ],
    'UBR': [ 'pyrimidine', true,  'U' ],
    'UD5': [ 'pyrimidine', false, 'U' ],
    'UFT': [ 'pyrimidine', true,  'U' ],
    'UMS': [ 'pyrimidine', true,  'U' ],
    'UMX': [ 'pyrimidine', true,  'U' ],
    'UPE': [ 'pyrimidine', true,  'U' ],
    'UPV': [ 'pyrimidine', false, 'U' ],
    'UR3': [ 'pyrimidine', false, 'U' ],
    'URX': [ 'pyrimidine', true,  'U' ],
    'US3': [ 'pyrimidine', true,  'T' ],
    'USM': [ 'pyrimidine', true,  'U' ],
    'UVX': [ 'pyrimidine', true,  'U' ],
    'XCY': [ 'pyrimidine', true,  'C' ],
    'YCO': [ 'pyrimidine', true,  'C' ],
      'Z': [ 'pyrimidine', true,  'C' ],
    'ZDU': [ 'pyrimidine', true,  'U' ],
    'CFL': [ 'pyrimidine', true,  'C' ],
      'C': [ 'pyrimidine', false, 'C' ],
    'C38': [ 'pyrimidine', true,  'C' ],
    'DOC': [ 'pyrimidine', true,  'C' ],
    'F2T': [ 'pyrimidine', false, 'U' ],
    'ME6': [ 'pyrimidine', true,  'C' ],
    'SPT': [ 'pyrimidine', true,  'T' ],
      'T': [ 'pyrimidine', true,  'T' ],
    'TPC': [ 'pyrimidine', true,  'C' ],
    'TCP': [ 'pyrimidine', true,  'T' ],
      'U': [ 'pyrimidine', false, 'U' ],
    'UMP': [ 'pyrimidine', true,  'U' ],
    '2DT': [ 'pyrimidine', true,  'T' ],
    'CFZ': [ 'pyrimidine', true,  'C' ],

    'PSU': [        'PSU', false, 'U' ]
} as const;

export type KnownBase = keyof typeof KnownBasesProps;
const _KnownBases = ObjectKeys(KnownBasesProps) as string[];

export const BackboneAtoms = {
    first: ["C5'", "C4'", "O4'", "C3'", "O3'", "C1'"],
    /* eslint-disable @typescript-eslint/quotes */
    second: ["P", "O5'", "C5'", "C4'", "O4'", "C3'", "O3'", "C1'"],
};

export const BaseAtoms: Record<Ring, string[]> = {
    purine: ['N9', 'C4'],
    pyrimidine: ['N1', 'C2'],
    PSU: ['C5', 'C4'],
};

export function isKnownBase(compId: string): compId is KnownBase {
    return _KnownBases.includes(compId);
}

export function referenceAtoms(compId: string, order: keyof typeof BackboneAtoms) {
    if (!isKnownBase(compId))
        return [];

    return [
        ...BackboneAtoms[order],
        ...BaseAtoms[KnownBasesProps[compId][0]]
    ];
}
